on:
  push:
    branches-ignore:
      - '**'
  workflow_dispatch:

env:
  GCS_BUCKET: ${{ secrets.GCS_CFB_PBP }}

jobs:
  sync-pbp-to-gcs:
    name: Sync cfbfastR pbp to GCS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: 'actions/checkout@v2'
      with:
        repository:  'sportsdataverse/cfbfastR-data@master'
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R ./pbp/parquet gs://$GCS_BUCKET

