on:
  push:
    branches-ignore:
      - '**'
  workflow_dispatch:

env:
  GCS_BUCKET: ${{ secrets.GCS_CFB_PBP }}

jobs:
  sync-pbp-to-gcs:
    name: Sync cfbfastR pbp to GCS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2      

    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true
        repository:  sportsdataverse/cfbfastR-data@master

    - name: Deploy
      run: |-
        gsutil -m rsync -R ./pbp/parquet gs://$GCS_BUCKET
